=== abdennour001/xslt-transformation-example/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- schema.xsd - An xsd document that lists all courses for a student. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--  Types  -->
<!--  idtype -->
<xs:simpleType name="idtype">
  <xs:restriction base="xs:string">
    <!--   well-known KSU ID pattern -->
    <xs:pattern value="[0-9]{9}"/>
  </xs:restriction>
</xs:simpleType>

<!--  passwordtype -->
<xs:simpleType name="passwordtype">
  <xs:restriction base="xs:string">
    <!--  password length has to be greater than 6  -->
    <xs:minLength value="6" />
  </xs:restriction>
</xs:simpleType>

<!--  courseidtype -->
<xs:simpleType name="courseidtype">
  <xs:restriction base="xs:string">
    <!--   well-known course_ID pattern -->
    <xs:pattern value="IT[0-9]{3}" />
  </xs:restriction>
</xs:simpleType>

<!--  statustype -->
<xs:simpleType name="statustype">
  <xs:restriction base="xs:string">
    <!--  status is current OR pass  -->
    <xs:pattern value="current|pass"/>
  </xs:restriction>
</xs:simpleType>

<!--  fortype -->
<xs:simpleType name="fortype">
  <xs:restriction base="xs:string">
    <!--  for is lecture OR lab  -->
    <xs:pattern value="lecture|lab"/>
  </xs:restriction>
</xs:simpleType>

<!--  texttype -->
<xs:simpleType name="texttype">
  <xs:restriction base="xs:string">
    <!--  type is book OR paper OR webpage  -->
    <xs:pattern value="book|paper|webpage"/>
  </xs:restriction>
</xs:simpleType>



<xs:element name="student">
  <xs:complexType>

    <!--  Nasted tags of student -->
    <xs:sequence>
      <!--  course-list tag  -->
      <xs:element name="course_list">
        <xs:complexType>
          <xs:sequence>
            <!--  The course tag  from 1 to +oo courses-->
            <xs:element name="course" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>

                <xs:sequence>

                  <!--  course_name tag  -->
                  <xs:element name="course_name" type="xs:string"/>

                  <!--  instructor tag  -->

                  <xs:element name="instructor" minOccurs="1" maxOccurs="4">
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:string">
                          <xs:attribute name="for" type="fortype" use="required"/>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>

                  <!--  credit_hours tag  -->
                  <xs:element name="credit_hours" type="xs:positiveInteger"/>

                  <!--  description tag  -->
                  <xs:element name="description" type="xs:string"/>

                  <!-- textbooks tag -->
                  <xs:element name="textbooks">
                    <xs:complexType>
                      <xs:sequence>

                        <!--  text tag  -->
                        <xs:element name="text" minOccurs="0" maxOccurs="20">
                          <xs:complexType>

                            <xs:sequence>

                              <!--  ISBN tag  -->
                              <xs:element name="ISBN" type="xs:string" minOccurs="0" maxOccurs="1"/>

                              <!--  title tag  -->
                              <xs:element name="title" type="xs:string"/>

                              <!--  author tag  -->
                              <xs:element name="author" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="fname" minOccurs="1" maxOccurs="1"/>
                                    <xs:element name="mname" minOccurs="0" maxOccurs="1"/>
                                    <xs:element name="lname" minOccurs="1" maxOccurs="1"/>
                                  </xs:sequence>
                                </xs:complexType>
                              </xs:element>

                              <!--  edition tag -->
                              <xs:element name="edition" type="xs:string" minOccurs="0" maxOccurs="1"/>

                              <!--  link tag -->
                              <xs:element name="link" type="xs:string" minOccurs="0" maxOccurs="1"/>

                            </xs:sequence>

                            <!--  Attributes of text  -->
                            <xs:attribute name="type" type="texttype" use="required"/>
                            <xs:attribute name="is_main" type="xs:boolean" use="required"/>


                          </xs:complexType>

                        </xs:element>

                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>

                </xs:sequence>

                <!--  Attributes of course  -->
                <xs:attribute name="course_ID" type="courseidtype" use="required"/>
                <xs:attribute name="status" type="statustype" default="current"/>

              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

    </xs:sequence>

    <!--  Attributes of student -->
    <xs:attribute name="ID" type="idtype" use="required"/>
    <xs:attribute name="password" type="passwordtype" use="required"/>

  </xs:complexType>
 </xs:element>
</xs:schema>

=== abdennour001/xslt-transformation-example/sample_student3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- sample_student1.xml - An xml document that lists all courses for a student1. -->

<!--  Assign the XSLT stylesheet to the xml file  -->
<?xml-stylesheet type="text/xsl" href="sample_student.xsl"?>

<!--  student has two attribute "ID" and "password" hash in MD5 Crypt  -->
<student ID="777112980"  password="5eb63bbbe01eeed093cb22bb8f5acdc3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

  <!-- course-list tag contains all courses, one nasted tag course with 1 to +oo appearence  -->
  <course_list>

    <!--  course tag has two attributes "course_ID" (as required attribute with pattern
          r"IT[0-9][0-9][0-9]") and "status" which can be 'current' (as default) or 'pass'
        -->
    <course course_ID="IT124" status="current">
      <!--  course-name as a string  -->
      <course_name>Beyond Survival (Fall 2010)</course_name>

      <!-- instructor tag contains the name of the instructor and his assignement as an
           attribute "for", 1-4
          -->
      <instructor for="lecture">Professor Michele Elam</instructor>
      <instructor for="lab">Professor Harry Elam</instructor>

      <!--  credit_hours is a number -->
      <credit_hours>10</credit_hours>

      <!--  description as a string  -->
      <description>Course Rationale:
How do men and women survive—not just physically, but intellectually, creatively, spiritually—in the world? Our course examines texts that imaginatively model strategies to overcome physical deprivation (everything from enslavement to prison camp confinement to sexual violence) and social oppression (from religious persecution to gender discrimination). How does a legacy of psychic and social trauma manifest itself in the contemporary moment? How does the past impact not only the present but subsequent generations, as in the children of survivors? How do the historical specificities into which we are born impact what constitutes survival in the first place—just what is to be endured, resisted, reconsidered, embraced at any given time? How do social differences, often specific to time and place, inform not only survival but the post-survival period? How are often transnational considerations of race, ethnicity and gender, in particular, made and unmade within these texts—and further, what are the narrative as well as political means and ends of race, ethnicity, gender, and religion in these works? We will examine these questions through works that range from the seventeenth century to the present. Significantly, all the contemporary texts look back to critical moments in the past.</description>

      <!--  textbooks contains the texts of the course 0-20 text can be uploaded  -->
      <textbooks>

        <!--  text tag contains the information about the course text  -->
        <!--  text1 : main course book "Basics of Web"-->
        <text type="book" is_main="true">
          <!--  ISBN : The International Standard Book Number of the book  -->
          <ISBN>978-3-16-148410-0</ISBN>
          <!--  title : A simple string  -->
          <title> Economic Analysis I</title>
          <!--  author : contains fname, mname (optional) and lname.  -->
          <author>
            <fname>AMOKRANE</fname>
            <mname>Abdennour</mname>
            <lname>Majid</lname>
          </author>

          <!--  edition (optional) "integer" -->
          <edition>2.1.0</edition>

          <!--  link (optional, i.e. if the type is webpage, or type book but it is an online
                book).
              -->
          <link>file:///C:/Users/asus/Downloads/EMD/Milestone-1.pdf</link>

        </text>

        <!--  text2 : secondary course paper "Basics of Web notes"-->
        <text type="paper" is_main="false">

          <title>Basics of Economics</title>
          <author>
            <fname>AMOKRANE</fname>
            <lname>Abdennour</lname>
          </author>
          <edition>3.2.1</edition>

        </text>

        <!--  text3 : main course web page "Web dev site"-->
        <text type="webpage" is_main="true">

          <title>Economics</title>
          <author>
            <fname>AMOKRANE</fname>
            <lname>Majid</lname>
          </author>
          <author>
            <fname>GUEDWAR</fname>
            <lname>Ahmed</lname>
          </author>
          <edition>5</edition>
          <link>https://www.chemistryworld.com/news/less-is-more-for-dna-reactions/5553.article</link>

        </text>

      </textbooks>

    </course>

  </course_list>

</student>

=== abdennour001/xslt-transformation-example/sample_student1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- sample_student1.xml - An xml document that lists all courses for a student1. -->

<!--  Assign the XSLT stylesheet to the xml file  -->
<?xml-stylesheet type="text/xsl" href="sample_student.xsl"?>

<!--  student has two attribute "ID" and "password" hash in MD5 Crypt  -->
<student ID="150018940"  password="5eb63bbbe01eeed093cb22bb8f5acdc3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

  <!-- course-list tag contains all courses, one nasted tag course with 1 to +oo appearence  -->
  <course_list>

    <!--  course tag has two attributes "course_ID" (as required attribute with pattern
          r"IT[0-9][0-9][0-9]") and "status" which can be 'current' (as default) or 'pass'
        -->
    <course course_ID="IT564" status="current">
      <!--  course-name as a string  -->
      <course_name>Modern Physics</course_name>

      <!-- instructor tag contains the name of the instructor and his assignement as an
           attribute "for", 1-4
          -->
      <instructor for="lecture">Marwan Suliman</instructor>
      <instructor for="lab">Sumaiya Begum</instructor>

      <!--  credit_hours is a number -->
      <credit_hours>30</credit_hours>

      <!--  description as a string  -->
      <description>“Modern Physics” is a phrase that generally refers to the most significant developments in physics in the past century: special relativity (appropriate for describing really fast stuff); quantum mechanics (necessary for describing really small stuff); atomic, molecular and laser physics; electronic materials (semiconductors); the elementary particles and the fundamental forces (the electromagnetic, weak and strong interactions); nuclear physics (fission, fusion and radioactivity), and astrophysics and cosmology (the contents and evolution of the universe). I will introduce you to amazing insights we have about the universe on length and time scales that span many, many orders of magnitude. As well as emphasizing the progress that has been made in our understanding of the universe, I will also point out the questions that remain open – questions that are currently the subject of active research at Stanford and elsewhere. I will describe how many of these seemingly esoteric topics touch on your everyday life and have led to most of the technological developments of the past century. Your view of the world will never be the same!</description>

      <!--  textbooks contains the texts of the course 0-20 text can be uploaded  -->
      <textbooks>

        <!--  text tag contains the information about the course text  -->
        <!--  text1 : main course book "Basics of Web"-->
        <text type="book" is_main="true">
          <!--  ISBN : The International Standard Book Number of the book  -->
          <ISBN>978-3-16-148410-0</ISBN>
          <!--  title : A simple string  -->
          <title>Basics of physics</title>
          <!--  author : contains fname, mname (optional) and lname.  -->
          <author>
            <fname>Sulaiman</fname>
            <mname>Lai</mname>
            <lname>Muhammed</lname>
          </author>

          <!--  edition (optional) "integer" -->
          <edition>2.0</edition>

          <!--  link (optional, i.e. if the type is webpage, or type book but it is an online
                book).
              -->

        </text>

        <!--  text2 : secondary course paper "Basics of Web notes"-->
        <text type="paper" is_main="false">

          <title>Physics notes</title>
          <author>
            <fname>Nawaf</fname>
            <lname>Sulaiman</lname>
          </author>

          <edition>fourth</edition>

        </text>

        <!--  text3 : main course web page "Web dev site"-->
        <text type="webpage" is_main="true">

          <title>teachingcommons</title>
          <author>
            <fname>AMOKRANE</fname>
            <lname>Majid</lname>
          </author>
          <author>
            <fname>GUEDWAR</fname>
            <lname>Ahmed</lname>
          </author>
          <edition>5.2</edition>
          <link>https://teachingcommons.stanford.edu</link>

        </text>

      </textbooks>

    </course>



    <course course_ID="IT212" status="pass">
      <!--  course-name as a string  -->
      <course_name>Web development</course_name>

      <!-- instructor tag contains the name of the instructor and his assignement as an
           attribute "for", 1-4
          -->
      <instructor for="lecture">AMOKRANE Abdennour</instructor>
      <instructor for="lab">MOHAMMED Abdel-jalil</instructor>

      <!--  credit_hours is a number -->
      <credit_hours>30</credit_hours>

      <!--  description as a string  -->
      <description>Course description here...</description>

      <!--  textbooks contains the texts of the course 0-20 text can be uploaded  -->
      <textbooks>

        <!--  text tag contains the information about the course text  -->
        <!--  text1 : main course book "Basics of Web"-->
        <text type="book" is_main="true">
          <!--  ISBN : The International Standard Book Number of the book  -->
          <ISBN>978-3-16-148410-0</ISBN>
          <!--  title : A simple string  -->
          <title>Basics of Web</title>
          <!--  author : contains fname, mname (optional) and lname.  -->
          <author>
            <fname>AMOKRANE</fname>
            <mname>Abdennour</mname>
            <lname>Majid</lname>
          </author>

          <!--  edition (optional) "integer" -->
          <edition>2</edition>

          <!--  link (optional, i.e. if the type is webpage, or type book but it is an online
                book).
              -->
          <link>file:///C:/Users/asus/Downloads/EMD/Milestone-1.pdf</link>

        </text>

        <!--  text2 : secondary course paper "Basics of Web notes"-->
        <text type="paper" is_main="false">

          <title>Basics of Web notes</title>
          <author>
            <fname>AMOKRANE</fname>
            <lname>Abdennour</lname>
          </author>

        </text>

        <!--  text3 : main course web page "Web dev site"-->
        <text type="webpage" is_main="true">

          <title>Web dev site</title>
          <author>
            <fname>AMOKRANE</fname>
            <lname>Majid</lname>
          </author>
          <author>
            <fname>GUEDWAR</fname>
            <lname>Ahmed</lname>
          </author>
          <edition>5</edition>
          <link>https://www.chemistryworld.com/news/less-is-more-for-dna-reactions/5553.article</link>

        </text>

      </textbooks>

    </course>

  </course_list>

</student>
